# Generated by Django 5.2.9 on 2025-12-23 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OilField',
            fields=[
                ('oil_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('operator_company', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(choices=[('pressure', 'Pressure'), ('temperature', 'Temperature'), ('flow_rate', 'Flow Rate')], max_length=20)),
                ('install_date', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionReading',
            fields=[
                ('reading_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('well_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('shut-in', 'Shut-in'), ('abandoned', 'Abandoned')], max_length=20)),
                ('drill_date', models.DateField()),
                ('depth_m', models.FloatField()),
                ('oil_field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='api.oilfield')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='well_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.well'),
        ),
    ]
